export const SET_LOADING = "SET_LOADING";
export const SET_CONTACT_LIST = "SET_CONTACT_LIST";
export const UPDATE_CONTACT_LIST = "UPDATE_CONTACT_LIST";
export const DELETE_CONTACT_LIST = "DELETE_CONTACT_LIST";
export const CREATE_CONTACT_LIST = "CREATE_CONTACT_LIST";
export const SET_ERROR = "SET_ERROR";
